"""empty message

Revision ID: 3b9947e5ae05
Revises: 8020aeda9b89
Create Date: 2021-10-16 15:09:21.405807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9947e5ae05'
down_revision = '8020aeda9b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'weight')
    # ### end Alembic commands ###
