"""empty message

Revision ID: 4d0367090b41
Revises: 220cbe1a485d
Create Date: 2021-09-23 18:30:46.632858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0367090b41'
down_revision = '220cbe1a485d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
