"""empty message

Revision ID: a410f4f83b56
Revises: 4d0367090b41
Create Date: 2021-09-25 22:36:46.560607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a410f4f83b56'
down_revision = '4d0367090b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('name', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'name')
    # ### end Alembic commands ###
